# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56a1ba4b7cc9bdcd6b0ab9276ff70c91c1e06b3a2cc03bd0c3f5051b4e2a71381faa26ba33b87bfbfd55bfa5b4a987902709cdd0b58172581ebfcb1b3a4c9784

test:
  secret_key_base: df091f08061de24dd397202d946e1aa733be5f57eb93e6c2226a2037e7737b12a97ddb90b1d33baa76a6920d1cd3254c922330ce2ac87f496bb14ec55f8b194c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
